name: Invitation to The Shield GitHub Community Organization
description: I would like to be part of the awesome community
title: "Please invite me to The Shield GitHub Community Organization"
labels: [Invitation to the community]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: twitter
    attributes:
      label: Twitter Username (if applicable)
      placeholder: Insert your Twitter username here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Where did you meet The shield? What do you like about this community/Why do you want to join?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can also join our Twitter community [here](https://twitter.com/Shield_Hackers)
        Feel free to check out other cool repositories of the The Shield Community [here](https://github.com/Th3-Shield)
